posts/urls.py
from django.conf.urls import url, include
from .views import post_list, post_detail, post_create, user_profile_page, PostLikeToggle

urlpatterns = [
    url(r'^$', post_list,name='post_list'),
    url(r'^detail/(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^create/$',post_create, name='create'),
    url(r'user/(?P<username>[\w-]+)/$', user_profile_page, name='user_profile_page'),
    url(r'^(?P<slug>[\w-]+)/like/$', PostLikeToggle.as_view(), name='like-toggle'),
]

simpleIns/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from accounts.views import login_view, register, logout_view, profile_edit_view
from simpleIns import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("posts.urls", namespace='posts')),
    url(r'^register/', register,name='register'),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^edit/', profile_edit_view, name='edit'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import string

from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.db import models
import random

# Create your models here.
from django.db.models.signals import pre_save
from django.template.defaultfilters import slugify
from django.urls import reverse
from PIL import Image

from accounts.models import UserProfile
from comments.models import Comment


def upload_location(instance, filename):
    username = instance.user.username
    new_id = instance.id
    return "%s/%s/%s" %(username, new_id, filename)


class Post(models.Model):
    user = models.ForeignKey(User)
    photo = models.ImageField(upload_to=upload_location,
                              null=False,
                              width_field="width_field",
                              height_field="height_field"
                              )
    description = models.CharField(max_length=512, default='')
    likes = models.ManyToManyField(User,related_name="user_like",blank=True)
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)
    publish = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.slug

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type

    @property
    def get_instance_comment(self):
        instance = self
        queryset = Comment.objects.filter_by_instance(instance).order_by('-timestamp')
        return queryset

    def get_like_url(self):
        return reverse("posts:like-toggle", kwargs={"slug": self.slug})

    def get_user_image(self):
        image = UserProfile.objects.get(user=self.user).image.url
        return image




def random_string_generator(size):
    chars = string.ascii_lowercase + string.digits
    return ''.join(random.choice(chars) for _ in range(size))


def unique_slug_generator(instance,new_slug=None):
    PostClass = instance.__class__
    if new_slug is not None:
        slug = new_slug
    else:
        slug = slugify(str(instance.user.username)+str("-")+str(instance.pk))
    qs_exists = PostClass.objects.filter(slug=slug).exists()
    if qs_exists:
        new_slug = "{slug}-{randstr}".format(
                    slug=slug,
                    randstr=random_string_generator(size=5)
                )
        return unique_slug_generator(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(pre_save_post_receiver, sender=Post)

posts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from urllib import quote_plus
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
# Create your views here.
from django.views.generic import RedirectView

from comments.forms import CommentForm
from posts.models import Post
from accounts.models import UserProfile
from comments.models import Comment


def post_list(request):
    if not request.user.is_authenticated:
        return redirect("/login")
    queryset_list = Post.objects.all()
    query = request.GET.get("q")
    title = "Home"
    if query:
        queryset_list = queryset_list.filter(
                Q(description__icontains=query)|
                Q(slug__icontains=query)|
                Q(user__username__icontains=query)
                ).distinct()
    paginator = Paginator(queryset_list, 8) # Show 25 contacts per page
    page_request_var = "page"
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)

    slug = request.GET.get("slug")
    if slug:
        obj = Post.objects.get(slug=slug)
        user = request.user
        if user in obj.likes.all():
            obj.likes.remove(user)
        else:
            obj.likes.add(user)
        obj.save()
    context = {
        "object_list": queryset,
        "page_request_var": page_request_var,
        "title":title
    }
    return render(request, "post_list.html", context)


def post_detail(request, slug=None):
    if not request.user.is_authenticated:
        return redirect("/login")
    title = "Detai"
    instance = get_object_or_404(Post, slug=slug)
    share_string = quote_plus(instance.description)

    if request.method=='POST':
        content = request.POST['content']
        content_type = instance.get_content_type
        email = request.user.email
        object_id = instance.id
        parent_obj = None
        try:
            parent_id = int(request.POST.get('parent_id'))
        except:
            parent_id = None
        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()
        comment = Comment.objects.create(user=request.user,
                                         content=content,
                                         content_type=content_type,
                                         email=email,
                                         object_id=object_id,
                                         parent=parent_obj)
        comment.save()
        return HttpResponseRedirect(comment.content_object.get_absolute_url())
    context = {
        "instance": instance,
        "share_string": share_string,
        # "comment_form": form,
        "title": title
    }

    return render(request, "post_detail.html", context)


class PostLikeToggle(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        slug = self.kwargs.get("slug")
        print(slug)
        obj = get_object_or_404(Post, slug=slug)
        url_ = obj.get_absolute_url()
        user = self.request.user
        if user.is_authenticated():
            if user in obj.likes.all():
                obj.likes.remove(user)
            else:
                obj.likes.add(user)
        print obj.likes.count()
        return url_


def post_create(request):
    if not request.user.is_authenticated:
        return redirect("/login")
    if request.method == 'POST':
        description = request.POST['description']
        try:
            photo = request.FILES['photo']
        except:
            messages.warning(request, "Not photo found!")
            return render(request, "post_form.html")
        post = Post.objects.create(user=request.user,
                                   description=description,
                                   photo=photo)
        post.save()
        messages.success(request, "Successfully posted!")
        return HttpResponseRedirect(post.get_absolute_url())
    return render(request, "post_form.html")


def user_profile_page(request, username):
    title = "User"
    current_user = request.user
    if not current_user.is_authenticated:
        return redirect("/login")
    global user_profile, user
    try:
        user = User.objects.get(username=username)
        user_profile = UserProfile.objects.get(user=user)
    except User.DoesNotExist:
        messages.warning(request, "User does not exist")
    except UserProfile.DoesNotExist:
        messages.warning(request, "User does not exist")

    posts = Post.objects.filter(user=user)
    context = {
        'title':title,
        'posts': posts,
        'user_profile': user_profile,
        'current_user':current_user
    }
    return render(request, 'profile_detail.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/base.css" %}">

    <!-- 可选的 Bootstrap 主题文件（一般不用引入） -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
      integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link href='http://fonts.googleapis.com/css?family=Oleo+Script' rel='stylesheet' type='text/css'>
    {% block link_file %}
    {% endblock link_file %}
    <title>{{ title }}</title>
</head>
<body>
{% block head %}
    <div class="navbar panel navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <h3 class="text-muted"> SimpleIns</h3>
            </div>
            <div class="right">
                 {% if not request.user.is_authenticated %}
                     <a class="main-menu--item text-muted" href='{% url "register" %}'>Register</a>
                     <a class="main-menu--item" href='{% url "login" %}'>Login</a>
                 {% else %}
                     <a class="main-menu--item" href="{% url 'posts:post_list' %}">Home</a>
                     <a class="main-menu--item" href='{% url "logout" %}'>Logout</a>
                    <a class="main-menu--item" href="{% url 'posts:create' %}">Create</a>
                    <a class="main-menu--item" href="{% url 'posts:user_profile_page' request.user.username %}">
                        <span class="glyphicon glyphicon-user"></span>
                    </a>
                     <div class="top main-menu--item" id="to_top">
                         <span class="glyphicon glyphicon-arrow-up"></span>
                     </div>

                 {% endif %}
            </div>
        </div>
    </div>







{% endblock head %}
{% block account_container %}
{% endblock account_container %}
{% block post_list_container %}
{% endblock post_list_container %}
{% block post_detail_container %}
{% endblock post_detail_container %}
{% block profile_container %}
{% endblock profile_container %}
{% block post_form_container %}
{% endblock post_form_container %}
<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"
integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
<script>
window.onload = function(){
    var oTop = document.getElementById("to_top");
    var screenw = document.documentElement.clientWidth || document.body.clientWidth;
    var screenh = document.documentElement.clientHeight || document.body.clientHeight;
    oTop.style.left = screenw - oTop.offsetWidth +"px";
    oTop.style.top = screenh - oTop.offsetHeight + "px";
    window.onscroll = function(){
    var scrolltop = document.documentElement.scrollTop || document.body.scrollTop;
    oTop.style.top = screenh - oTop.offsetHeight + scrolltop +"px";
    };
    oTop.onclick = function(){
    document.documentElement.scrollTop = document.body.scrollTop =0;
    }
}

</script>
<script>
  var fileInput = document.querySelector('input[type=file]'),
          previewImg = document.querySelector('img');
  fileInput.addEventListener('change', function () {
      var file = this.files[0];
      var reader = new FileReader();
      reader.addEventListener("load", function () {
          previewImg.src = reader.result;
      }, false);
      reader.readAsDataURL(file);
  }, false);
</script>
</body>
</html>

templates/form.html
{% extends 'base.html' %}
{% load static %}
{% block link_file %}
    <link rel="stylesheet" href="{% static "css/login.css" %}">
{% endblock link_file %}
{% block account_container %}
    <div class='lg-container'>
    <h1>{{ title }}</h1>
    <hr/>
        <div>
            <form method='POST' action='' enctype='multipart/form-data' id="lg-form">{% csrf_token %}
                <div class="form-group">
                    {{ form.as_p }}
                    {% if form.get_form == "registerForm" or form.get_form == "editForm" %}
                    <button class="btn btn-default" type="button" onclick="file.click()">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add Your Image
                    </button>
                </div>
                <div class="form-group">
                    <img class="img-responsive" src="" alt="" title="preview-img">
                </div>
                    {% endif %}
                <div class="form-group">
                    <input type='submit' class='btn btn-primary {{ title }}' value='{% if form.get_form != "editForm" %} {{ title }} {% else %} Save {% endif %}' id="login"/>
                    <input type='reset' class='btn btn-default' value='Reset' id="reset"/>
                </div>
            </form>
        </div>
    </div>

{% endblock account_container %}

templates/post_detail.html
{% extends "base.html" %}
{% load static %}
{% block link_file %}
        <link rel="stylesheet" href="{% static "css/rest.css" %}">
{% endblock link_file %}
{% block post_detail_container %}
<div>
<div>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="thumbnail">
             <img src='{{ instance.photo.url }}' class='img-responsive' />
            <a class='like-btn'
            data-likes='{{ instance.likes.count }}'
            href='{{ instance.get_like_url }}'>{{ instance.likes.count }} likes</a>
          <div class="caption post-detail-item">
              <h3 class="text-muted">
                  {{ instance.description }} <small>{{ instance.publish|timesince }}</small>
              </h3>
          </div>
        </div>
      </div>
    <br>
    </div>
</div>
<footer>
    <div class="col-md-6 col-md-offset-3">

        <form class="form-horizontal" action="{% url 'posts:detail' instance.slug %}" method="POST">{% csrf_token %}
            <div class="form-group">
                <input type="text" name="content"  class="form-control" placeholder="Say something?">
            </div>
            <div class="form-group">
                <input type="submit" value="Commit" class="btn btn-default">
            </div>
        </form>
    </div>
    <div class="row">
        {% for comment in instance.get_instance_comment %}
            <div class="col-md-6 col-md-offset-3">
            <blockquote>
                <div class="row">
                    <a href="{% url 'posts:user_profile_page' comment.user.username %}">
                        <div class="col-md-1">
                            <img src="{{ comment.user.user_profile.image.url }}" style="height: 50px; width: 50px" class="img-circle">
                        </div>
                        <div class="col-md-1">
                            <p class="text-info">
                                {{ comment.user.username }}:
                            </p>
                        </div>
                    </a>
                    <div class="col-md-1 col-md-offset-1">
                        <p class="text-info">
                            {{ comment.content }}
                        </p>
                    </div>
                </div>
                <div>
                    {% for children_comment in comment.children %}
                        <blockquote>
                            <div class="row">
                                <a href="{% url 'posts:user_profile_page' children_comment.user.username %}">
                                    <div class="col-md-1">
                                            <img src="{{ children_comment.user.user_profile.image.url }}" style="height: 30px; width: 30px" class="img-circle">
                                    </div>
                                    <div class="col-md-1">
                                        <p class="text-info">
                                            {{ children_comment.user.username }}:
                                        </p>
                                    </div>
                                </a>
                                <div class="col-md-1 col-md-offset-1">
                                    <p class="text-info">
                                        {{ children_comment.content }}
                                    </p>
                                </div>
                            </div>
                        </blockquote>
                    {% endfor %}
                    <form class="form-horizontal" action="{% url 'posts:detail' instance.slug %}" method="POST">{% csrf_token %}
                        <div class="form-group">
                            <input type="text" name="content"  class="form-control" placeholder="Say something?">
                            <input type="hidden" name="parent_id" value="{{ comment.id }}">
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Reply" class="btn btn-default">
                        </div>
                    </form>
                </div>
            </blockquote>
            </div>
        {% endfor %}

    </div>
</footer>
</div>
{% endblock post_detail_container %}

templates/post_form.html
{% extends 'base.html' %}
{% load static %}
{% block link_file %}
    <link rel="stylesheet" href="{% static "css/rest.css" %}">
{% endblock link_file %}
{% block post_form_container %}
    <div class="blank">

    </div>
<div class="col-md-6 col-md-offset-3">
    <form method='POST' action='{% url 'posts:create' %}' enctype='multipart/form-data'>{% csrf_token %}

        <div class="form-group">
            <button class="btn btn-default" type="button" onclick="file.click()">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add Your Image
            </button>
            <input type="file" id="file" name="photo" class="form-control" style="display: none">
        </div>
        <div class="form-group">
            <img src="" class="img-responsive" alt=" Preview of the Image. . . " title="preview-img">
        </div>

        <div class="form-group">
            <input type="text" class="form-control" name="description" placeholder='Say something...'/>
        </div>
        <input type='submit' class='btn btn-primary' value='Create Post' />
    </form>
</div>
{% endblock post_form_container %}

templates/post_list.html
{% extends "base.html" %}
{% load static %}
{% block link_file %}
    <link rel="stylesheet" href="{% static "css/rest.css" %}">
{% endblock link_file %}
{% block post_list_container %}
        <div class="row">
            <div class='col-md-6 col-sm-offset-3'>
                <form method='GET' action=''>
                    <div class='col-md-6'>
                        <div class='input-group'>
                            <input class='form-control' type='text' name='q' placeholder='Search posts' value='{{ request.GET.q }}'/>
                            <span class='input-group-btn'>
                        <!-- <input class='btn btn-default' type='submit' value='Search' /> -->
                        <button class='btn btn-default' type='submit'>
                            <span class="glyphicon glyphicon-search"></span>
                            Search <i class="fa fa-search"></i>
                        </button>
                    </span>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <br>
        <div>
            {% for obj in object_list %}
                <div class="row">
                    <div class="col-md-6 col-md-offset-3">
                        <div class="thumbnail">
                            <a href='{{ obj.get_absolute_url }}'><img src='{{ obj.photo.url }}' class='img-responsive' /></a>
                            <a class="user-like" href="{% url 'posts:post_list' %}?slug={{ obj.slug }}">
                                <span class="badge">{{ obj.likes.count }}</span>
                                likes
                            </a><small>{{ obj.get_instance_comment.count }} comments</small>
                            {#                <input type="button" value="like" onclick="liked({{ obj.slug }})">#}
                            <div>
                                <div class="obj-user">
                                    <a class="main-menu--item" href="{% url 'posts:user_profile_page' obj.user.username %}">
                                        <img src="{{ obj.get_user_image }}" style="width: 50px; height: 50px" class="img-circle"/>
                                        <p class="user-username"> {{ obj.user.username }} </p>
                                    </a>
                                </div>
                                <div class="description">
                                    <h3>
                                        <a class="description" href='{{ obj.get_absolute_url }}'>{{ obj.description }}</a>
                                    </h3><small>{{ obj.publish }}</small>
                                    <br>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <!--pagination-->
    <nav aria-label="pagination">
      <ul class="pager">
              {% if object_list.has_previous %}
            <li>
                <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">
                    <span aria-hidden="true">&larr;previous</span>
                </a>
            </li>
              {% endif %}
            <li>
                <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
                </span>
            </li>
            {% if object_list.has_next %}
            <li>
                <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">
                    <span aria-hidden="true">&rarr;next</span>
                </a>
            </li>
            {% endif %}
      </ul>
    </nav>
{#        <div class="pagination">#}
{#    <span class="step-links">#}
{#        {% if object_list.has_previous %}#}
{#            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>#}
{#        {% endif %}#}
{##}
{#        <span class="current">#}
{#            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.#}
{#        </span>#}
{##}
{#        {% if object_list.has_next %}#}
{#            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>#}
{#        {% endif %}#}
{#    </span>#}
{#        </div>#}



{% endblock post_list_container %}
{#{% load staticfiles %}#}
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->#}
{#<link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"#}
{#      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">#}
{##}
{#<!-- 可选的 Bootstrap 主题文件（一般不用引入） -->#}
{#<link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"#}
{#      integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">#}
{#    <link rel="stylesheet" href="{% static css/ %}">#}
{#    <title>List</title>#}
{#</head>#}
{#<body>#}
{##}
{#    <div>#}
{#        <a href="{% url 'posts:create' %}">Create</a>#}
{#    </div>#}
{#    <div>#}
{#            {% if not request.user.is_authenticated %}#}
{#            <li class='pull-right'><a href='{% url "register" %}'>Register</a></li>#}
{#            <li class='pull-right'><a href='{% url "login" %}'>Login</a></li>#}
{#            {% else %}#}
{#            <li class='pull-right'><a href='{% url "logout" %}'>Logout</a></li>#}
{#            {% endif %}#}
{#    </div>#}
{#    <div>#}
{#        <form method='GET' action='' class='row'>#}
{#            <div class='col-md-6 col-md-offset-3'>#}
{#                <div class='input-group'>#}
{#                    <input class='form-control' type='text' name='q' placeholder='Search' value='{{ request.GET.q }}'/>#}
{#                    <span class='input-group-btn'>#}
{#                        <!-- <input class='btn btn-default' type='submit' value='Search' /> -->#}
{#                        <button class='btn btn-default' type='submit'>Search <i class="fa fa-search"></i></button>#}
{#                    </span>#}
{#                </div>#}
{#            </div>#}
{#        </form>#}
{#    </div>#}
{##}
{#    <div>#}
{#        {% for obj in object_list %}#}
{#            <div class="row">#}
{#              <div class="col-md-6 col-md-offset-3">#}
{#                <div class="thumbnail">#}
{#                    <a href='{{ obj.get_absolute_url }}'><img src='{{ obj.photo.url }}' class='img-responsive' /></a>#}
{#                    <a href="{% url 'posts:post_list' %}?slug={{ obj.slug }}">{{ obj.likes.count }} likes</a>#}
{#                    <input type="button" value="like" onclick="liked({{ obj.slug }})">#}
{#                  <div class="">#}
{#                      <a href="{% url 'posts:user_profile_page' obj.user.username %}">#}
{#                          <img src="{{ obj.get_user_image }}" style="width: 50px; height: 50px" class="img-circle"/>#}
{#                          <p> {{ obj.user.username }} </p>#}
{#                      </a>#}
{#                  </div>#}
{#                    <div>#}
{#                      <h3 class="lead">#}
{#                          <a href='{{ obj.get_absolute_url }}'>{{ obj.description }}</a> <small>{{ obj.publish }}</small>#}
{#                      </h3>#}
{#                  </div>#}
{#                </div>#}
{#              </div>#}
{#            <hr/>#}
{#            </div>#}
{#        {% endfor %}#}
{#    </div>#}
{##}
{#    <!--pagination-->#}
{#    <div class="pagination">#}
{#        <span class="step-links">#}
{#            {% if object_list.has_previous %}#}
{#                <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>#}
{#            {% endif %}#}
{##}
{#            <span class="current">#}
{#                Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.#}
{#            </span>#}
{##}
{#            {% if object_list.has_next %}#}
{#                <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>#}
{#            {% endif %}#}
{#        </span>#}
{#    </div>#}
{#<script>#}
{#    function liked (slug) {#}
{#        alert("hi");#}
{#        $.ajax({#}
{#            url:{% url 'posts:post_list' %},#}
{#            type:'GET',#}
{#            data:{'slug':slug},#}
{#            success: function () {#}
{#                alert("Success");#}
{#            }#}
{#        });#}
{#    }#}
{#</script>#}
{#<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->#}
{#<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"#}
{#integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>#}
{#<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>#}
{##}
{#</body>#}
{#</html>#}

templates/profile_detail.html
{% extends 'base.html' %}
{% load static %}
{% block link_file %}
        <link rel="stylesheet" href="{% static "css/rest.css" %}">
{% endblock link_file %}
{% block profile_container %}
<div>
    <div class="row">
        <div class="col-md-1 col-md-offset-1"></div>
        <div class="col-md-1 col-md-offset-1">
            <img id="profile-image" src="{{ user_profile.image.url }}" class="img-circle" style="height: 150px; width: 150px;"/>
        </div>
        <div class="col-md-3 col-sm-offset-1">
            <p class="lead user-username">{{ user_profile.user.username }}</p>
            <p class="signature">{{ user_profile.signature }}</p>
            {% if user_profile.user.username == current_user.username %}
            <button class="edit-profile btn btn-default" type="button">
                <a class="edit-profile" href="{% url 'edit' %}">
                    <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                    Edit Profile
                </a>
            </button>
            {% endif %}
        </div>
    </div>
</div>
<br>
<div>
        {% for obj in posts %}
      <div class="col-md-6 col-md-offset-3">
        <div class="thumbnail">
             <img src='{{ obj.photo.url }}' class='img-responsive' />
          <div class="caption post-detail-item">
              <h3>
                  <a href='{{ obj.get_absolute_url }}'>{{ obj.description }}</a> <small>{{ obj.publish }}</small>
              </h3>
          </div>
        </div>
      </div>
    <br>
        {% endfor %}
    </div>
</div>
{% endblock profile_container %}